### ISSUE TITLE
Mikstura THICK nie istnieje w klasie Potions na wersji 1.14.2

### ISSUE THREAD

**Issue by Mroczny-rgb** [Craftserve/CraftserveRadiation#22]
Gdy wrzucam plugin na serwer w najnowszej wersji plugin nie jest aktywny co zrobić ?

**Comment by Mroczny-rgb** [comment]
![Adnotacja 2020-03-05 164311](https://user-images.githubusercontent.com/61759323/75997990-71140e80-5f00-11ea-8194-79eb21bf7e84.png)

**Comment by TheMolkaPL** [comment]
Pokaż logi

**Comment by Mroczny-rgb** [comment]
```
06.03 19:50:41 [Server] Server thread/WARN Can't keep up! Is the server overloaded? Running 2182ms or 43 ticks behind
06.03 19:50:38 [Disconnect] User com.mojang.authlib.GameProfile@388cbd8d[id=c28d8468-2dbf-3c0b-960e-afd59f2e5b15,name=alan127,properties={},legacy=false] (/109.199.11.34:51537) has disconnected, reason: Disconnected
06.03 19:50:38 [Disconnect] User com.mojang.authlib.GameProfile@32457d82[id=246bb8f4-dac1-396b-a9b1-52ed5081f373,name=Mixkubix1234,properties={},legacy=false] (/188.146.235.13:23893) has disconnected, reason: Disconnected
06.03 19:50:38 [Disconnect] User com.mojang.authlib.GameProfile@68109eba[id=246bb8f4-dac1-396b-a9b1-52ed5081f373,name=Mixkubix1234,properties={},legacy=false] (/188.146.235.13:23880) has disconnected, reason: Disconnected
06.03 19:50:37 [Server] Startup Done (93.049s)! For help, type "help"
06.03 19:50:36 [Server] Server thread/INFO Server permissions file permissions.yml is empty, ignoring it
06.03 19:50:36 [Server] INFO ... 11 more
06.03 19:50:36 [Server] INFO at pl.craftserve.radiation.nms.V1_14ToV1_15NmsBridge.<init>(V1_14ToV1_15NmsBridge.java:38) ~[?:?]
06.03 19:50:36 [Server] INFO at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_242]
06.03 19:50:36 [Server] INFO Caused by: java.lang.NoSuchFieldException: THICK
06.03 19:50:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
06.03 19:50:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot114.jar:git-Spigot-c8d4cef-1fee35b]
06.03 19:50:36 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot114.jar:git-Spigot-c8d4cef-1fee35b]
06.03 19:50:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot114.jar:git-Spigot-c8d4cef-1fee35b]
06.03 19:50:36 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot114.jar:git-Spigot-c8d4cef-1fee35b]
06.03 19:50:36 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot114.jar:git-Spigot-c8d4cef-1fee35b]
06.03 19:50:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot114.jar:git-Spigot-c8d4cef-1fee35b]
06.03 19:50:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot114.jar:git-Spigot-c8d4cef-1fee35b]
06.03 19:50:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot114.jar:git-Spigot-c8d4cef-1fee35b]
06.03 19:50:36 [Server] INFO at pl.craftserve.radiation.RadiationPlugin.onEnable(RadiationPlugin.java:67) [CraftserveRadiation-1.1.2.jar:?]
06.03 19:50:36 [Server] INFO at pl.craftserve.radiation.RadiationPlugin.initializeNmsBridge(RadiationPlugin.java:56) ~[CraftserveRadiation-1.1.2.jar:?]
06.03 19:50:36 [Server] INFO at pl.craftserve.radiation.nms.V1_14ToV1_15NmsBridge.<init>(V1_14ToV1_15NmsBridge.java:41) ~[CraftserveRadiation-1.1.2.jar:?
```

**Comment by TheMolkaPL** [comment]
Wygląda na bug. Pokaż w takim razie jeszcze wersję Spigota - wpisz komendę `/version`.

**Comment by Mroczny-rgb** [comment]
![Adnotacja 2020-03-06 214242](https://user-images.githubusercontent.com/61759323/76121241-7aca6e80-5ff3-11ea-8db5-6685421d61b2.png)

**Comment by TheMolkaPL** [comment]
Na ten moment mogę ci jedynie zaproponować aktualizację Spigota do wersji 1.14.4, czyli najnowszej wersji 1.14.

Powiązane: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/builddata/commits/fb5e14fce5af96290063bf4ee833c2ad72bef028#mappings/bukkit-1.14.2-members.csrg
