### ISSUE TITLE
Strefa Radiacji - pomoc 

### ISSUE THREAD

**Issue by ryaNNNq** [Craftserve/CraftserveRadiation#34]
Witam, mam problem, ponieważ plugin nie jest wykrywany. Jest wgrany, a w grze po wpisaniu komendy /pl nawet sie nie wyswietla. Chodzi mi tu o najnowsza wersje.

**Comment by TheMolkaPL** [comment]
Poproszę logi z uruchomienia serwera. Znajdziesz je w pliku `latest.log` w folderze `logs`.

**Comment by ryaNNNq** [comment]
Niestety aktualnie hosting na ktorym posiadam serwer, ma chyba problemy techniczne i nie moge sie polaczyc z FTP, wysle logi najszybciej jak to bedzie mozliwe. (WebFTP tez nie dziala) Serwer tez aktualnie nie dziala.

**Comment by ryaNNNq** [comment]
```
*** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
Loading libraries, please wait...
[20:03:31] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[20:03:32] [main/INFO]: Reloading ResourceManager: Default, bukkit
[20:03:34] [Worker-Main-2/INFO]: Loaded 7 recipes
[2K[20:03:31] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[2K[20:03:32] [main/INFO]: Reloading ResourceManager: Default, bukkit
[2K[20:03:34] [Worker-Main-2/INFO]: Loaded 7 recipes
[2K[20:03:35] [Server thread/INFO]: Starting minecraft server version 1.16.1
[2K[20:03:35] [Server thread/INFO]: Loading properties
[20:03:36] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-c3a49df-2f18108 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[20:03:36] [Server thread/INFO]: Debug logging is disabled
[20:03:36] [Server thread/INFO]: Server Ping Player Sample Count: 12
[20:03:36] [Server thread/INFO]: Using 4 threads for Netty based IO
[20:03:36] [Server thread/INFO]: Default game type: SURVIVAL
[20:03:36] [Server thread/INFO]: Generating keypair
[20:03:36] [Server thread/INFO]: Starting Minecraft server on 54.38.131.87:25565
[20:03:37] [Server thread/INFO]: Using epoll channel type
[20:03:37] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[20:03:44] [Server thread/WARN]: Legacy plugin PermissionsEx v1.23.4 does not specify an api-version.
[20:03:44] [Server thread/WARN]: Legacy plugin TimeIsMoney v1.9.6.11 does not specify an api-version.
[20:03:44] [Server thread/ERROR]: Could not load 'plugins/CraftserveRadiation-1.2-pre4 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[mc.jar:git-Spigot-c3a49df-2f18108]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[mc.jar:git-Spigot-c3a49df-2f18108]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[mc.jar:git-Spigot-c3a49df-2f18108]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:382) ~[mc.jar:git-Spigot-c3a49df-2f18108]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:186) ~[mc.jar:git-Spigot-c3a49df-2f18108]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[mc.jar:git-Spigot-c3a49df-2f18108]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[mc.jar:git-Spigot-c3a49df-2f18108]
at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
at pl.craftserve.radiation.RadiationPlugin.<clinit>(RadiationPlugin.java:50) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:416) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[mc.jar:git-Spigot-c3a49df-2f18108]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[mc.jar:git-Spigot-c3a49df-2f18108]
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
at java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[mc.jar:git-Spigot-c3a49df-2f18108]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[mc.jar:git-Spigot-c3a49df-2f18108]
at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
[20:03:44] [Server thread/WARN]: Legacy plugin VanishNoPacket v3.20.1 does not specify an api-version.
[20:03:44] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.1.0;8e55131
[20:03:44] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@680e4954]
[20:03:44] [Server thread/INFO]: [SkinsRestorer] Loading SkinsRestorer v13.8.2
[20:03:44] [Server thread/INFO]: [Skript] Loading Skript v2.5-alpha6(rev1)
[20:03:44] [Server thread/INFO]: [LogBlock] Loading LogBlock v1.15.2
[20:03:44] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.10.6
[20:03:44] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[20:03:45] [Server thread/WARN]: [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!
[20:03:45] [Server thread/INFO]: [PlugMan] Loading PlugMan v2.1.7
[20:03:45] [Server thread/INFO]: [SkQuery] Loading SkQuery v3.6.5
[20:03:45] [Server thread/INFO]: [Vault] Loading Vault v1.7.2-b107
[20:03:45] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.4-beta1;bc551da
[20:03:45] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.5.0
[20:03:45] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.16.1) has not yet been tested! Proceed with caution.
[20:03:45] [Server thread/INFO]: [Essentials] Loading Essentials v2.18.0.0
[20:03:46] [Server thread/WARN]: [WorldEdit] ====================================================
[20:03:46] [Server thread/WARN]: [WorldEdit] WorldEdit works better if you use Paper
[20:03:46] [Server thread/WARN]: [WorldEdit] as your server software.
[20:03:46] [Server thread/WARN]: [WorldEdit]
[20:03:46] [Server thread/WARN]: [WorldEdit] Paper offers significant performance improvements,
[20:03:46] [Server thread/WARN]: [WorldEdit] bug fixes, security enhancements and optional
[20:03:46] [Server thread/WARN]: [WorldEdit] features for server owners to enhance their server.
[20:03:46] [Server thread/WARN]: [WorldEdit] Paper includes Timings v2, which is significantly
[20:03:46] [Server thread/WARN]: [WorldEdit] better at diagnosing lag problems over v1.
[20:03:46] [Server thread/WARN]: [WorldEdit] All of your plugins should still work, and the
[20:03:46] [Server thread/WARN]: [WorldEdit] Paper community will gladly help you fix any issues.
[20:03:46] [Server thread/WARN]: [WorldEdit] Join the Paper Community @ https://papermc.io
[20:03:46] [Server thread/INFO]: [Vault] Enabling Vault v1.7.2-b107
[20:03:46] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.18.0.0 which is not a depend, softdepend or loadbefore of this plugin.
[20:03:46] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[20:03:46] [Server thread/WARN]: [Vault] Loaded class ru.tehkode.permissions.bukkit.PermissionsEx from PermissionsEx v1.23.4 which is not a depend, softdepend or loadbefore of this plugin.
[20:03:46] [Server thread/INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[20:03:46] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[20:03:46] [Server thread/INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[20:03:46] [Server thread/INFO]: [Vault] Enabled Version 1.7.2-b107
[20:03:46] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[20:03:46] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.5.0
[20:03:46] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[20:03:46] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[20:03:46] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[20:03:46] [Server thread/WARN]: While this makes the game possible to play wit
```

**Comment by TheMolkaPL** [comment]
Zostało naprawione w https://github.com/Craftserve/CraftserveRadiation/commit/4f0bdaab754d2d6aea061e2fb4e417c29e05202e. Do czasu nowego release pluginu mogę Ci jedynie polecić zmianę Spigota na Paper
