### ISSUE TITLE
Plugin się nie uruchamia

### ISSUE THREAD

**Issue by kostek001** [Craftserve/CraftserveRadiation#35]
Przy uruchamianiu pluginu na Spigocie 1.16.1 wyskakuje taki błąd, a plugin się nie uruchamia.

Błąd:
[10:25:54] [Server thread/INFO]: Starting minecraft server version 1.16.1
[10:25:54] [Server thread/INFO]: Loading properties
[10:25:55] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[10:25:56] [Server thread/INFO]: Debug logging is disabled
[10:25:56] [Server thread/INFO]: Server Ping Player Sample Count: 12
[10:25:56] [Server thread/INFO]: Using 4 threads for Netty based IO
[10:25:56] [Server thread/INFO]: Default game type: SURVIVAL
[10:25:56] [Server thread/INFO]: Generating keypair
[10:25:57] [Server thread/INFO]: Starting Minecraft server on *:25565
[10:25:57] [Server thread/INFO]: Using default channel type
[10:26:08] [Server thread/ERROR]: Could not load 'plugins\CraftserveRadiation-1.2-pre4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:382) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:186) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at pl.craftserve.radiation.RadiationPlugin.<clinit>(RadiationPlugin.java:50) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at pl.craftserve.radiation.RadiationPlugin.<clinit>(RadiationPlugin.java:50) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        ... 7 more
[10:26:08] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.0-beta-03+94ce464
[10:26:11] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@4212dd59]
[10:26:11] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.4-beta1;bc551da
[10:26:11] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.0-beta-03+94ce464

**Comment by TheMolkaPL** [comment]
Duplikat #34
