### ISSUE TITLE
Naprawcie metricsy

### ISSUE THREAD

**Issue by XANT3R** [Craftserve/CraftserveRadiation#40]
Od dłuższego czasu wasze metricsy w konsoli sypią errorami 

[21:54:27] [Metrics-Lite-Submitter/ERROR]: [pl.craftserve.metrics.pluginmetricslite.MetricsLite] Could not submit report 0269fb62-cac7-44e1-b853-fe9b6002bb44 for Metrics Lite
java.io.IOException: Request returned 400, 200 or 204 was expected.
    at pl.craftserve.metrics.pluginmetricslite.UrlEndpoint.submit(UrlEndpoint.java:85) ~[?:?]
    at pl.craftserve.metrics.pluginmetricslite.MetricsLite$Reporter.run(MetricsLite.java:268) ~[?:?]
    at java.util.TimerThread.mainLoop(Timer.java:556) ~[?:?]
    at java.util.TimerThread.run(Timer.java:506) ~[?:?]

Mam tym w tym całą konsolę. Taki błąd występuje co kilka sekund.

**Comment by Morlineq** [comment]
Mam ten sam problem ;d

**Comment by mrozo94** [comment]
Workaround, który nie jest na pewno pożądany przez twórców pluginu, ale robi robotę. Zwłaszcza że ostatnimi czasy spam w logach, przynajmniej u mnie osiągnął nowy poziom i realnie wpływa na wydajność serwera.

Wystarczy wykomentować w pliku `src/main/java/pl/craftserve/radiation/RadiationPlugin.java`  pole `private MetricsHandler metricsHandler` oraz następnie wszystkie jego użycia w tej samej klasie. Potem budujemy całość i gotowe.

EDIT: Jeśli twórcom pasuje taki workaround, proszę o informację, chętnie dam MR do mastera. @TheMolkaPL

**Comment by Cubixmeister** [comment]
@Rekseto zajrzysz w to api na produkcyjnym panelu?
