### ISSUE TITLE
Metrics spami błędami w konsoli

### ISSUE THREAD

**Issue by Morlineq** [Craftserve/CraftserveRadiation#41]
Co około pół minuty wciąż pojawia się błąd w konsoli:

```
[11:52:39] [Metrics-Lite-Submitter/ERROR]: [pl.craftserve.metrics.pluginmetricslite.MetricsLite] Could not submit report b00c7671-f7e4-4f95-82c7-4cc0c6dc348d for Metrics Lite
java.io.IOException: Request returned 400, 200 or 204 was expected.
	at pl.craftserve.metrics.pluginmetricslite.UrlEndpoint.submit(UrlEndpoint.java:85) ~[?:?]
	at pl.craftserve.metrics.pluginmetricslite.MetricsLite$Reporter.run(MetricsLite.java:268) ~[?:?]
	at java.util.TimerThread.mainLoop(Timer.java:556) ~[?:?]
	at java.util.TimerThread.run(Timer.java:506) ~[?:?]
```

Zaczyna się pojawiać około 4 godzin od włączenia serwera, zaśmieca on konsole. Najnowsza wersja pluginu.

**Comment by TheMolkaPL** [comment]
Duplikat #40
