### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by ghost** [Craftserve/CraftserveRadiation#47]
Hi! Plugin has an internal error on 1.18.2
![image](https://user-images.githubusercontent.com/45406683/159061532-b088ef96-6519-42f3-baa0-1b84fe52c493.png)

**Comment by ghost** [comment]
[19:39:49 ERROR]: [pl.craftserve.radiation.RadiationPlugin] Failed to launch CraftserveRadiation. Plausibly your server version is unsupported.
java.lang.RuntimeException: Unsupported server version: v1_18_R2
at pl.craftserve.radiation.RadiationPlugin.initializeNmsBridge(RadiationPlugin.java:102) ~[CraftserveRadiation-1.4.jar:?]
at pl.craftserve.radiation.RadiationPlugin.onEnable(RadiationPlugin.java:123) ~[CraftserveRadiation-1.4.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1596]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1596]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1596]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1596]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1596]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1596]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1596]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Cubixmeister** [comment]
We'll be happy to review a pull request

**Comment by TheMolkaPL** [comment]
1.18.2 JAR can be downloaded from my fork until the update is merged: https://github.com/TheMolkaPL/CraftserveRadiation/releases
