### ISSUE TITLE
Could not submit report for Metrics Lite

### ISSUE THREAD

**Issue by mrozo94** [Craftserve/CraftserveRadiation#51]
Mam problem z Waszym pluginem, mianowicie z błędami dot. MetricsLite - proszę o pomoc, bądź nakierowanie jak sobie z nimi poradzić.

<details>
<summary>LOG: java.net.UnknownHostException: craftserve.pl </summary>

```
[02:08:55 ERROR]: [pl.craftserve.metrics.pluginmetricslite.MetricsLite] Could not submit report 2bbff8de-d62e-4841-a12c-8a8e2f916c34 for Metrics Lite
java.net.UnknownHostException: craftserve.pl
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220) ~[?:?]
        at pl.craftserve.metrics.pluginmetricslite.UrlEndpoint.submit(UrlEndpoint.java:70) ~[CraftserveRadiation-1.4.jar:?]
        at pl.craftserve.metrics.pluginmetricslite.MetricsLite$Reporter.run(MetricsLite.java:268) ~[CraftserveRadiation-1.4.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.util.TimerThread.run(Timer.java:516) ~[?:?]
```
</details>

<details>
  <summary>LOG: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake </summary>

```
[13:01:28 ERROR]: [pl.craftserve.metrics.pluginmetricslite.MetricsLite] Could not submit report 541c8db8-8541-4e80-85c1-064883bffcee for Metrics Lite
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1709) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220) ~[?:?]
        at pl.craftserve.metrics.pluginmetricslite.UrlEndpoint.submit(UrlEndpoint.java:70) ~[CraftserveRadiation-1.4.jar:?]
        at pl.craftserve.metrics.pluginmetricslite.MetricsLite$Reporter.run(MetricsLite.java:268) ~[CraftserveRadiation-1.4.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.util.TimerThread.run(Timer.java:516) ~[?:?]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500) ~[?:?]
        ... 12 more
```
</details>

~~Będę szykował wsparcie do 1.19~~ _(już ktoś zrobił)_ i przy okazji chciałbym poprawić również to, ale potrzebowałbym małej pomocy.

**Comment by TheMolkaPL** [comment]
Duplikat #40.

Plugin posiada wbudowane wysyłanie metryk do [bStats](https://bstats.org/plugin/bukkit/CraftserveRadiation/13487). Metryki do Craftserve nie są zaimplementowane po stronie serwera i pewnie nigdy nie będą. Ich wysyłanie odbywa się poprzez bibliotekę [PluginMetrics](https://github.com/Craftserve/PluginMetrics) z klasy MetricsHandler:

https://github.com/Craftserve/CraftserveRadiation/blob/abe0018ee7be3e75a65bb3d3aca8c9dc26414a90/src/main/java/pl/craftserve/radiation/MetricsHandler.java#L55-L59

https://github.com/Craftserve/CraftserveRadiation/blob/abe0018ee7be3e75a65bb3d3aca8c9dc26414a90/src/main/java/pl/craftserve/radiation/MetricsHandler.java#L66-L70

https://github.com/Craftserve/CraftserveRadiation/blob/abe0018ee7be3e75a65bb3d3aca8c9dc26414a90/src/main/java/pl/craftserve/radiation/MetricsHandler.java#L99-L115

Do bStats wysyłane są praktycznie takie same dane.

**Comment by mrozo94** [comment]
Dzięki za info :) Na pewno będzie przytadne!
