### ISSUE TITLE
[Metrics-Lite-Submitter/ERROR]

### ISSUE THREAD

**Issue by legendofgow** [Craftserve/CraftserveRadiation#54]
Wyskoczył błąd i po tym wyrzuciło wszystkich z serwera, czy to wina ze strony wtyczki?

[17:34:58] [Metrics-Lite-Submitter/ERROR]: [pl.craftserve.metrics.pluginmetricslite.MetricsLite] Could not submit report 66418f6a-0f8f-4bb3-b001-7013007fbf5a for Metrics Lite
java.net.UnknownHostException: craftserve.pl
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220) ~[?:?]
	at pl.craftserve.metrics.pluginmetricslite.UrlEndpoint.submit(UrlEndpoint.java:70) ~[CraftserveRadiation-1.5.jar:?]
	at pl.craftserve.metrics.pluginmetricslite.MetricsLite$Reporter.run(MetricsLite.java:268) ~[CraftserveRadiation-1.5.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
	at java.util.TimerThread.run(Timer.java:516) ~[?:?]
[17:34:59] [Server thread/INFO]: __Magda__ lost connection: Timed out
[17:34:59] [Server thread/INFO]: Tostowy_lisek lost connection: Timed out
[17:34:59] [Server thread/INFO]: magma_flame lost connection: Timed out
[17:34:59] [Server thread/INFO]: [-] Gracz magma_flame
[17:35:00] [Server thread/INFO]: Pucateq issued server command: /tpa Kpytko94
[17:35:00] [Server thread/INFO]: NiezgodnaNZG lost connection: Timed out
[17:35:00] [Server thread/INFO]: [-] Vip NiezgodnaNZG

**Comment by Cubixmeister** [comment]
Duplikat #40
