### ISSUE TITLE
Błąd w konsoli

### ISSUE THREAD

**Issue by egebege231** [Craftserve/CraftserveRadiation#58]
Błąd w konsoli, powtarza sie co minutę
Silnik: Purpur 1.19.2

[11:52:45 ERROR]: [pl.craftserve.metrics.pluginmetricslite.MetricsLite] Could not submit report c51ef5b0-1a2f-4ef0-b1f5-03d5e147f166 for Metrics Lite
java.io.IOException: Request returned 403, 200 or 204 was expected.
        at pl.craftserve.metrics.pluginmetricslite.UrlEndpoint.submit(UrlEndpoint.java:85) ~[CraftserveRadiation-1.6.1.jar:?]
        at pl.craftserve.metrics.pluginmetricslite.MetricsLite$Reporter.run(MetricsLite.java:268) ~[CraftserveRadiation-1.6.1.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.util.TimerThread.run(Timer.java:516) ~[?:?]

**Comment by egebege231** [comment]
z 1.6.2 wersja jest tak samo

**Comment by TheMolkaPL** [comment]
Duplikat #40.
