### ISSUE TITLE
Wsparcie dla wyższych wersji

### ISSUE THREAD

**Issue by jbzdyyy** [Craftserve/CraftserveRadiation#59]
Witam, plugin najprawdopodobniej nie wspiera wyższych wersji: logi
`[pl.craftserve.radiation.RadiationPlugin] Failed to launch CraftserveRadiation. Plausibly your server version is unsupported.java.lang.RuntimeException: Unsupported server version: v1_20_R3at pl.craftserve.radiation.RadiationPlugin.initializeNmsBridge(RadiationPlugin.java:102) ~[CraftserveRadiation-1.4.jar:?]at pl.craftserve.radiation.RadiationPlugin.onEnable(RadiationPlugin.java:123) ~[CraftserveRadiation-1.4.jar:?]at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2159]at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2159]at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2159]at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2159]at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2159]at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2159]at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2159]at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2159]at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2159]at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Comment by hjfdaisgijhbdfsuw** [comment]
nie wspiera tez wersji 1.21.1
[14:14:07] [Server thread/INFO]: [CraftserveRadiation] Enabling CraftserveRadiation v1.6.2
[14:14:07] [Server thread/INFO]: [pl.craftserve.radiation.RadiationPlugin] Detected server version: craftbukkit
[14:14:07] [Server thread/ERROR]: [pl.craftserve.radiation.RadiationPlugin] Failed to launch CraftserveRadiation. Plausibly your server version is unsupported.
java.lang.RuntimeException: Unsupported server version: craftbukkit
	at CraftserveRadiation-1.6.2.jar/pl.craftserve.radiation.RadiationPlugin.initializeNmsBridge(RadiationPlugin.java:112) ~[CraftserveRadiation-1.6.2.jar:?]
	at CraftserveRadiation-1.6.2.jar/pl.craftserve.radiation.RadiationPlugin.onEnable(RadiationPlugin.java:133) ~[CraftserveRadiation-1.6.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Oskicz** [comment]
bump

**Comment by zwirzaky** [comment]
bump
